"""Add paused status customer_id task

Revision ID: 14ebe1b501b0
Revises: 3084aaf9f413
Create Date: 2026-05-16 22:18:16.406866

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14ebe1b501b0'
down_revision: Union[str, Sequence[str], None] = '3084aaf9f413'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tasks', sa.Column('customer_id', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tasks', 'customer_id')
    # ### end Alembic commands ###
